# Generated by Django 5.1.1 on 2024-09-17 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('rols', models.CharField(max_length=255, verbose_name='Должность')),
                ('image', models.ImageField(upload_to='about_emp/', verbose_name='Фото')),
                ('desc_1', models.TextField(verbose_name='Описание 1')),
                ('desc_2', models.TextField(verbose_name='Описание 2')),
                ('banner', models.ImageField(upload_to='about_banner/', verbose_name='Баннер')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
        migrations.CreateModel(
            name='AboutDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('image', models.ImageField(upload_to='about_doc/', verbose_name='Фото')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_doc', to='secondary.about')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
            },
        ),
        migrations.CreateModel(
            name='AboutService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_service', to='secondary.about')),
            ],
            options={
                'verbose_name': 'Услуги о нас',
                'verbose_name_plural': 'Услуги о нас',
            },
        ),
    ]
