# Generated by Django 5.1.1 on 2024-09-18 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0003_consultation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationProgres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consult_progres', to='secondary.consultation')),
            ],
            options={
                'verbose_name': ('Консультация',),
                'verbose_name_plural': 'Консультация',
            },
        ),
    ]
