# Generated by Django 5.1.1 on 2024-09-18 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0004_consultationprogres'),
    ]

    operations = [
        migrations.CreateModel(
            name='Methods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('text', models.TextField(verbose_name='текс для внимание')),
                ('subtitle', models.CharField(max_length=255, verbose_name='Последний текст')),
            ],
            options={
                'verbose_name': ('Метод',),
                'verbose_name_plural': 'Методы',
            },
        ),
    ]
