# Generated by Django 5.1.1 on 2024-09-18 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0006_methodseva'),
    ]

    operations = [
        migrations.CreateModel(
            name='MethodsDev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('methods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='methods_dev', to='secondary.methods')),
            ],
            options={
                'verbose_name': 'Приборы',
                'verbose_name_plural': 'Приборы',
            },
        ),
    ]
