# Generated by Django 5.1.1 on 2024-09-18 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0007_methodsdev'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название учреждения')),
                ('text_position', models.CharField(choices=[('top', 'Текст сверху'), ('bottom', 'Текст снизу')], default='none', max_length=10, verbose_name='Расположение текста')),
            ],
            options={
                'verbose_name': 'Учреждение',
                'verbose_name_plural': 'Учреждения',
            },
        ),
    ]
