# Generated by Django 5.1.1 on 2024-09-18 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0009_methodsemp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('appointment_date', models.CharField(max_length=255, verbose_name='Дата и время записи')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('description', models.TextField(verbose_name='Описание')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Запрос на контакт',
                'verbose_name_plural': 'Запросы на контакт',
            },
        ),
    ]
