# Generated by Django 5.1.1 on 2025-06-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0010_contactrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=233, verbose_name='Заголовок')),
                ('subtitle', models.CharField(max_length=244, verbose_name='Подзаголовок')),
                ('image', models.ImageField(upload_to='news', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Баннер новостей',
                'verbose_name_plural': 'Баннер новостей',
            },
        ),
    ]
