# Generated by Django 5.1.1 on 2025-06-21 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0011_newsbanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsbanner',
            name='description',
            field=models.TextField(default=1, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='NewsBannerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news', verbose_name='Изображение')),
                ('newsbanner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_banner_image', to='secondary.newsbanner')),
            ],
            options={
                'verbose_name': 'Изобрежение для новостей',
                'verbose_name_plural': 'Изобрежение для новостей',
            },
        ),
    ]
