# Generated by Django 5.1.1 on 2025-06-21 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0012_newsbanner_description_newsbannerimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsbanner',
            name='image',
        ),
    ]
