# Generated by Django 5.1.1 on 2025-07-06 12:53

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0015_alter_news_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='desc_1',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание 1'),
        ),
        migrations.AlterField(
            model_name='about',
            name='desc_2',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание 2'),
        ),
    ]
