# Generated by Django 5.1.1 on 2025-07-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0016_alter_about_desc_1_alter_about_desc_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='city',
            field=models.CharField(default='Бишкек', max_length=50, verbose_name='Город'),
        ),
    ]
