# Generated by Django 5.1.1 on 2025-07-10 09:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0017_contactrequest_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='methods',
            name='desc',
            field=ckeditor.fields.RichTextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='methods',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='текс для внимание'),
        ),
    ]
