# Generated by Django 5.1.1 on 2025-07-25 07:04

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0018_alter_methods_desc_alter_methods_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScientificJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('image', models.ImageField(upload_to='scientific/journals/', verbose_name='Изображение')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='scientific/journals/pdf/', verbose_name='PDF файл')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Научный журнал',
                'verbose_name_plural': 'Научные журналы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ScientificManual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='scientific/manuals/', verbose_name='Изображение')),
                ('pdf_file', models.FileField(upload_to='scientific/manuals/pdf/', verbose_name='PDF файл')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Учебно-методическое пособие',
                'verbose_name_plural': 'Учебно-методические пособия',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ScientificPatent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patent_number', models.CharField(max_length=50, verbose_name='Номер патента')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='scientific/patents/', verbose_name='Изображение')),
                ('pdf_file', models.FileField(upload_to='scientific/patents/pdf/', verbose_name='PDF файл')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Патент',
                'verbose_name_plural': 'Патенты',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ScientificPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('permission', 'Разрешение'), ('certificate', 'Свидетельство')], default='permission', max_length=20, verbose_name='Тип документа')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='scientific/permissions/', verbose_name='Изображение')),
                ('pdf_file', models.FileField(upload_to='scientific/permissions/pdf/', verbose_name='PDF файл')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Разрешение/Свидетельство',
                'verbose_name_plural': 'Разрешения/Свидетельства',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ScientificPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='scientific/publications/', verbose_name='Изображение')),
                ('pdf_file', models.FileField(upload_to='scientific/publications/pdf/', verbose_name='PDF файл')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Научная публикация',
                'verbose_name_plural': 'Научные публикации',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ScientificWorkIntro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Содержание')),
            ],
            options={
                'verbose_name': 'Введение научной работы',
                'verbose_name_plural': 'Введение научной работы',
            },
        ),
    ]
