# Generated by Django 5.1.1 on 2025-07-31 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0019_scientificjournal_scientificmanual_scientificpatent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationprogres',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='consult_progres/', verbose_name='Изображение'),
        ),
    ]
