# Generated by Django 5.1.1 on 2025-08-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0020_consultationprogres_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scientificmanual',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='scientific/manuals/pdf/', verbose_name='PDF файл'),
        ),
        migrations.AlterField(
            model_name='scientificpatent',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='scientific/patents/pdf/', verbose_name='PDF файл'),
        ),
        migrations.AlterField(
            model_name='scientificpermission',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='scientific/permissions/pdf/', verbose_name='PDF файл'),
        ),
        migrations.AlterField(
            model_name='scientificpublication',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='scientific/publications/pdf/', verbose_name='PDF файл'),
        ),
    ]
