# Generated by Django 5.1.1 on 2025-08-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0023_alter_news_content_alter_news_short_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScientificJournalsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Научные журналы', max_length=255, verbose_name='Заголовок раздела')),
                ('description', models.TextField(blank=True, help_text='Текст под заголовком в разделе научных журналов', null=True, verbose_name='Описание раздела')),
            ],
            options={
                'verbose_name': 'Секция журналов (заголовок и описание)',
                'verbose_name_plural': 'Секция журналов (заголовок и описание)',
            },
        ),
        migrations.CreateModel(
            name='ScientificManualsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Учебно-методические пособия', max_length=255, verbose_name='Заголовок раздела')),
                ('description', models.TextField(blank=True, help_text='Текст под заголовком в разделе учебно-методических пособий', null=True, verbose_name='Описание раздела')),
            ],
            options={
                'verbose_name': 'Секция пособий (заголовок и описание)',
                'verbose_name_plural': 'Секция пособий (заголовок и описание)',
            },
        ),
        migrations.CreateModel(
            name='ScientificPatentsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Патенты, свидетельства и разрешения', max_length=255, verbose_name='Заголовок раздела')),
                ('description', models.TextField(blank=True, help_text='Текст под заголовком в разделе патентов/разрешений', null=True, verbose_name='Описание раздела')),
            ],
            options={
                'verbose_name': 'Секция патентов (заголовок и описание)',
                'verbose_name_plural': 'Секция патентов (заголовок и описание)',
            },
        ),
        migrations.CreateModel(
            name='ScientificPublicationsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Опубликованные научные и клинические исследования', max_length=255, verbose_name='Заголовок раздела')),
                ('description', models.TextField(blank=True, help_text='Текст под заголовком в разделе публикаций', null=True, verbose_name='Описание раздела')),
            ],
            options={
                'verbose_name': 'Секция публикаций (заголовок и описание)',
                'verbose_name_plural': 'Секция публикаций (заголовок и описание)',
            },
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-published_at', '-created_at'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AddField(
            model_name='news',
            name='published_at',
            field=models.DateField(blank=True, null=True, verbose_name='Дата публикации'),
        ),
    ]
