# Generated by Django 5.1.1 on 2025-08-14 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0024_scientificjournalssection_scientificmanualssection_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactrequest',
            name='appointment_date',
        ),
    ]
