# Generated by Django 5.1.1 on 2025-08-25 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0025_remove_contactrequest_appointment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='methods',
            name='subtitle',
            field=models.TextField(verbose_name='Последний текст'),
        ),
        migrations.AlterField(
            model_name='methodsemp',
            name='desc',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
