# Generated by Django 5.1.1 on 2025-08-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0026_alter_methods_subtitle_alter_methodsemp_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='methodsdev',
            name='title',
            field=models.TextField(verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='methodseva',
            name='title',
            field=models.TextField(verbose_name='Заголовок'),
        ),
    ]
