# Generated by Django 5.1.1 on 2024-09-17 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0002_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
    ]
