# Generated by Django 5.1.1 on 2024-09-17 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0003_alter_service_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='service',
            name='desc',
            field=models.TextField(default=1, verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
