# Generated by Django 5.1.1 on 2024-09-17 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0004_remove_service_subtitle_service_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_created=True, blank=True, null=True, verbose_name='Дата')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('text', models.TextField(verbose_name='Отзыв')),
            ],
        ),
    ]
