# Generated by Django 5.1.1 on 2024-09-17 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0006_alter_reviews_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='create_at',
            field=models.DateField(auto_created=True, blank=True, null=True, verbose_name='Дата'),
        ),
    ]
