# Generated by Django 5.1.1 on 2024-09-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0009_remove_treatresult_treat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('rols', models.CharField(max_length=255, verbose_name='Должность')),
                ('image', models.ImageField(upload_to='employe/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': ('Сотрудник',),
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
