# Generated by Django 5.1.1 on 2024-09-17 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0010_employe'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='slug',
            field=models.SlugField(default=1, max_length=255, unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
