# Generated by Django 5.1.1 on 2024-09-17 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0011_employe_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='slug',
            field=models.SlugField(max_length=255, verbose_name='Slug'),
        ),
    ]
