# Generated by Django 5.1.1 on 2024-09-17 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0013_alter_employe_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
