# Generated by Django 5.1.1 on 2024-09-17 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0014_alter_employe_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='slug',
        ),
    ]
