# Generated by Django 5.1.1 on 2024-09-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0015_remove_employe_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='certificate',
            field=models.TextField(blank=True, null=True, verbose_name='Информация о сертификатах'),
        ),
        migrations.AddField(
            model_name='employe',
            name='diplom_info',
            field=models.TextField(blank=True, null=True, verbose_name='Информация о дипломе'),
        ),
        migrations.AddField(
            model_name='employe',
            name='evidence',
            field=models.TextField(blank=True, null=True, verbose_name='Информация о свидетельстве'),
        ),
        migrations.AddField(
            model_name='employe',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='employe/', verbose_name='Фото 2'),
        ),
    ]
