# Generated by Django 5.1.1 on 2024-09-18 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0017_videoreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='WriteReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='write_riviews/', verbose_name='Фото отзыва')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Рукописный отзыв',
                'verbose_name_plural': 'Рукописныйе отзывы',
            },
        ),
    ]
