# Generated by Django 5.1.1 on 2024-09-18 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0018_writereview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='writereview',
            options={'verbose_name': 'Рукописный отзыв', 'verbose_name_plural': 'Рукописные отзывы'},
        ),
    ]
