# Generated by Django 5.1.1 on 2024-09-18 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0019_alter_writereview_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='service_image', verbose_name='Фото')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_image', to='setting.service')),
            ],
            options={
                'verbose_name': 'Фото услуг',
                'verbose_name_plural': 'Фото услуги',
            },
        ),
    ]
