# Generated by Django 5.1.1 on 2024-09-18 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0021_servicestate'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Одобрен'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Отзыв'),
        ),
    ]
