# Generated by Django 5.1.1 on 2024-09-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0022_reviews_first_name_reviews_is_approved_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название сайта')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('logo', models.ImageField(upload_to='logo/', verbose_name='Логотип сайта')),
                ('address', models.CharField(max_length=244, verbose_name='Адрес')),
                ('schedul', models.CharField(max_length=244, verbose_name='График работы')),
                ('youtube', models.URLField(verbose_name='Ссылка на youtube')),
                ('facebook', models.URLField(verbose_name='Cсылка на facebook')),
                ('instagram', models.URLField(verbose_name='Ссылка на instagram')),
            ],
            options={
                'verbose_name': 'Настройки',
                'verbose_name_plural': 'Настройки',
            },
        ),
    ]
