# Generated by Django 5.1.1 on 2024-09-18 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0023_setting'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=255, verbose_name='Номер телефона')),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setting_phone', to='setting.setting')),
            ],
            options={
                'verbose_name': 'Номер телефона',
            },
        ),
    ]
