# Generated by Django 5.1.1 on 2024-09-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0025_treat_descrition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treat',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок'),
        ),
    ]
