# Generated by Django 5.1.1 on 2024-09-24 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0026_alter_treat_subtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='treat_image/', verbose_name='Фото')),
                ('treat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treats_image', to='setting.treat')),
            ],
            options={
                'verbose_name': 'Фото для что мы лечим',
                'verbose_name_plural': 'Фото для что мы лечим',
            },
        ),
    ]
