# Generated by Django 5.1.1 on 2025-06-17 09:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0027_treatimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='logo_footer',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='logo/', verbose_name='Логотип футера'),
            preserve_default=False,
        ),
    ]
