# Generated by Django 5.1.1 on 2025-06-22 13:34

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0028_setting_logo_footer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treat',
            name='descrition',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
