# Generated by Django 5.1.1 on 2025-07-06 12:38

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0029_alter_treat_descrition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='desc',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание'),
        ),
    ]
