# Generated by Django 5.1.1 on 2025-07-10 09:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0030_alter_service_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='certificate',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Информация о сертификатах'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='diplom_info',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Информация о дипломе'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='evidence',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Информация о свидетельстве'),
        ),
    ]
