# Generated by Django 5.1.1 on 2025-07-13 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0031_alter_employe_certificate_alter_employe_diplom_info_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('image', models.ImageField(upload_to='main_slider/', verbose_name='Изображение слайдера')),
            ],
            options={
                'verbose_name': 'Слайд главной страницы',
                'verbose_name_plural': 'Слайд главной страницы',
            },
        ),
    ]
