# Generated by Django 5.1.1 on 2025-07-28 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0032_mainslider'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treat',
            old_name='descrition',
            new_name='description',
        ),
    ]
