# Generated by Django 5.1.1 on 2025-07-28 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0033_rename_descrition_treat_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок')),
                ('image', models.ImageField(upload_to='slider/', verbose_name='Изображение слайдера')),
            ],
            options={
                'verbose_name': 'Слайд главной страницы',
                'verbose_name_plural': 'Слайд главной страницы',
            },
        ),
    ]
