# Generated by Django 5.1.1 on 2025-08-01 02:09

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0033_add_order_to_mainslider'),
    ]

    operations = [
        migrations.AddField(
            model_name='treat',
            name='description2',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
