# Generated by Django 5.1.1 on 2025-08-01 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0034_treat_description2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treat',
            name='description',
        ),
    ]
