# Generated by Django 5.1.1 on 2025-08-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0035_remove_treat_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='QR-код WhatsApp', max_length=255, verbose_name='Название')),
                ('qr_image', models.ImageField(upload_to='whatsapp_qr/', verbose_name='QR-код WhatsApp')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'QR-код WhatsApp',
                'verbose_name_plural': 'QR-коды WhatsApp',
            },
        ),
    ]
