# Generated by Django 5.1.1 on 2025-08-17 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0036_whatsappqr'),
    ]

    operations = [
        migrations.AddField(
            model_name='treat',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='treat/', verbose_name='Изображение'),
        ),
    ]
