# Generated by Django 5.1.1 on 2025-08-23 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0037_treat_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='address_2',
            field=models.CharField(blank=True, max_length=244, null=True, verbose_name='Адрес второй клиники'),
        ),
        migrations.AddField(
            model_name='setting',
            name='email_1',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email первой клиники'),
        ),
        migrations.AddField(
            model_name='setting',
            name='email_2',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email второй клиники'),
        ),
        migrations.AddField(
            model_name='setting',
            name='map_embed_url',
            field=models.TextField(blank=True, null=True, verbose_name='Ссылка на карту (embed)'),
        ),
        migrations.AddField(
            model_name='setting',
            name='schedul_2',
            field=models.CharField(blank=True, max_length=244, null=True, verbose_name='График работы второй клиники'),
        ),
        migrations.AddField(
            model_name='setting',
            name='telegram',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на Telegram'),
        ),
        migrations.AddField(
            model_name='setting',
            name='vk',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на VK'),
        ),
        migrations.AddField(
            model_name='setting',
            name='whatsapp',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на WhatsApp'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='address',
            field=models.CharField(max_length=244, verbose_name='Адрес первой клиники'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='Cсылка на facebook'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на instagram'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='schedul',
            field=models.CharField(max_length=244, verbose_name='График работы первой клиники'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='youtube',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на youtube'),
        ),
    ]
