# Generated by Django 5.1.1 on 2025-08-31 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0038_setting_address_2_setting_email_1_setting_email_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoreview',
            name='video',
            field=models.URLField(verbose_name='Ссылка на YouTube видео'),
        ),
    ]
