# Generated by Django 5.1.1 on 2025-10-18 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0039_alter_videoreview_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoreview',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='video_reviews/', verbose_name='Баннер видео (необязательно, если не указан - будет использовано превью из YouTube)'),
        ),
    ]
